### ISSUE TITLE
小白咨询：冲顶大会问题搜索的截图截到评论区

### ISSUE THREAD

**Issue by kakarottoll** [rrdssfgcs/wenda-helper#10]
修改了window.py里面parse_answer_area方法的 region = image.crop((0, 100, wide, 500))  
500改为300没有效果，请问是我修改错了嘛

**Comment by rrdssfgcs** [comment]
是否已经解决？是改这个函数的

**Comment by DrMewo** [comment]
改完运行main.py，不要运行exe
