### ISSUE TITLE
点击F2后出现错误，一直刷NOT IMPLEMENTED

### ISSUE THREAD

**Issue by sunweipo** [rrdssfgcs/wenda-helper#12]
![image](https://user-images.githubusercontent.com/31875507/34938141-25097664-fa22-11e7-8b39-bb60453addfa.png)

**Comment by rrdssfgcs** [comment]
这个错误应该是驱动的问题，不影响正常流程。

**Comment by sunweipo** [comment]
影响流程的啊，一直刷这个就是不去自动搜索
