### ISSUE TITLE
截图以后图片都不是窗口正中间

### ISSUE THREAD

**Issue by jsnjfz** [rrdssfgcs/wenda-helper#4]
截图以后图片都不是窗口正中间是什么原因，都有一定像素的偏差

**Comment by xue-dada** [comment]
我也遇到这个问题了，右击-->显示设置-->文本、应用和其它项目里的大小改为：100%
参考：
https://stackoverflow.com/questions/25467288/pils-imagegrab-is-capturing-at-the-wrong-resolution

**Comment by jsnjfz** [comment]
已经解决了，谢谢
