### ISSUE TITLE
一定要夜神模拟器吗，其他的行不行，比如说mumu

### ISSUE THREAD

**Issue by wsh1108** [rrdssfgcs/wenda-helper#8]
一定要夜神模拟器吗，其他的行不行，比如说mumu

**Comment by rrdssfgcs** [comment]
可以的，配置文件里把模拟器的名字改一下就行啦~要模拟器打开的窗口名

**Comment by carolcoral** [comment]
请问我用 mac 上的 xcode 模拟行不行了

**Comment by 1445453337** [comment]
请问怎么使用android的真机来识别

**Comment by rrdssfgcs** [comment]
@carolcoral 感觉那样需要改代码

**Comment by rrdssfgcs** [comment]
@1445453337 那样adb传输会用几秒时间，不如用模拟器

**Comment by carolcoral** [comment]
好的吧，谢谢了，那我还是用虚拟机来试试吧
