### ISSUE TITLE
google搜索还是不支持啊！

### ISSUE THREAD

**Issue by lweo** [rrdssfgcs/wenda-helper#9]
config里已改为google，能打开google首页，但识别后不搜索。。

**Comment by tj646** [comment]
如果用GOOGLE搜索把main.py里的“kw”换成"lst-ib"就可以了

**Comment by lweo** [comment]
@tj646  还是不能搜索啊，提示
[45904:17124:0115/144144.041:ERROR:process_metrics.cc(105)] NOT IMPLEMENTED

**Comment by rrdssfgcs** [comment]
@lweo 这个错误应该与谷歌搜索无关，是驱动的问题

**Comment by rrdssfgcs** [comment]
@tj646正解
